services:
  api:
    container_name: api
    build: ./src/api/
    ports:
      - 5000:5000
    volumes:
      - ./src/api:/app
    restart: always
  nginx:
    container_name: nginx
    build:
      context: ./src/frontend/
    ports:
      - 8080:80
    restart: always
    depends_on:
      - api

